In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [6]:
my_list1 = [1,2,3,4]

In [9]:
my_array1 = np.array(my_list1)

In [10]:
my_array1

array([1, 2, 3, 4])

In [11]:
my_list2 = [11,22,33,44]

In [12]:
my_lists = [my_list1, my_list2]

In [13]:
my_array2 = np.array(my_lists)

In [14]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [15]:
my_array2.shape

(2, 4)

In [16]:
my_array2.dtype

dtype('int32')

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype

dtype('float64')

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(5)

array([2.12199579e-314, 2.81899926e-308, 3.75489891e-321, 1.02280197e-311,
       1.14489383e+243])

In [23]:
np.empty(5)

array([2.12199579e-314, 2.81899926e-308, 3.75489891e-321, 1.02280197e-311,
       1.14489383e+243])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])