In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.42191306,  0.67253507, -0.88375049,  3.53821058, -0.08727853,
       -1.53708222, -0.43139921,  0.61612263,  0.12217147,  1.04494767])

In [8]:
B = np.random.randn(10)

In [10]:
B

array([-0.11726205,  0.74790571, -0.7678104 ,  0.25101272,  1.38314256,
        3.18223176, -1.31653775,  1.03923238, -0.38179722, -0.54398089])

In [11]:
# Binary Functions
np.add(A,B)

array([ 0.30465101,  1.42044078, -1.65156089,  3.7892233 ,  1.29586402,
        1.64514954, -1.74793696,  1.65535501, -0.25962575,  0.50096678])

In [12]:
np.maximum(A,B)

array([ 0.42191306,  0.74790571, -0.7678104 ,  3.53821058,  1.38314256,
        3.18223176, -0.43139921,  1.03923238,  0.12217147,  1.04494767])

In [13]:
np.minimum(A,B)

array([-0.11726205,  0.67253507, -0.88375049,  0.25101272, -0.08727853,
       -1.53708222, -1.31653775,  0.61612263, -0.38179722, -0.54398089])

In [15]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True